// flow-typed signature: 8d05a0c69b06c8cb3de99a3f5b51c4dc
// flow-typed version: <<STUB>>/babel-polyfill_v^6.16.0/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-polyfill/browser' {
  declare module.exports: any;
}

declare module 'babel-polyfill/dist/polyfill' {
  declare module.exports: any;
}

declare module 'babel-polyfill/dist/polyfill.min' {
  declare module.exports: any;
}

declare module 'babel-polyfill/lib/index' {
  declare module.exports: any;
}

declare module 'babel-polyfill/scripts/postpublish' {
  declare module.exports: any;
}

declare module 'babel-polyfill/scripts/prepublish' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-polyfill/browser.js' {
  declare module.exports: $Exports<'babel-polyfill/browser'>;
}
declare module 'babel-polyfill/dist/polyfill.js' {
  declare module.exports: $Exports<'babel-polyfill/dist/polyfill'>;
}
declare module 'babel-polyfill/dist/polyfill.min.js' {
  declare module.exports: $Exports<'babel-polyfill/dist/polyfill.min'>;
}
declare module 'babel-polyfill/lib/index.js' {
  declare module.exports: $Exports<'babel-polyfill/lib/index'>;
}
declare module 'babel-polyfill/scripts/postpublish.js' {
  declare module.exports: $Exports<'babel-polyfill/scripts/postpublish'>;
}
declare module 'babel-polyfill/scripts/prepublish.js' {
  declare module.exports: $Exports<'babel-polyfill/scripts/prepublish'>;
}
