// flow-typed signature: e1f7abbd4e173b59d393a418d78a44c6
// flow-typed version: <<STUB>>/materialize-css_v^0.98.2/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'materialize-css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'materialize-css' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'materialize-css/bin/materialize' {
  declare module.exports: any;
}

declare module 'materialize-css/dist/js/materialize' {
  declare module.exports: any;
}

declare module 'materialize-css/dist/js/materialize.min' {
  declare module.exports: any;
}

declare module 'materialize-css/extras/noUiSlider/nouislider' {
  declare module.exports: any;
}

declare module 'materialize-css/extras/noUiSlider/nouislider.min' {
  declare module.exports: any;
}

declare module 'materialize-css/Gruntfile' {
  declare module.exports: any;
}

declare module 'materialize-css/jade/lunr.min' {
  declare module.exports: any;
}

declare module 'materialize-css/jade/search' {
  declare module.exports: any;
}

declare module 'materialize-css/js/animation' {
  declare module.exports: any;
}

declare module 'materialize-css/js/buttons' {
  declare module.exports: any;
}

declare module 'materialize-css/js/cards' {
  declare module.exports: any;
}

declare module 'materialize-css/js/carousel' {
  declare module.exports: any;
}

declare module 'materialize-css/js/character_counter' {
  declare module.exports: any;
}

declare module 'materialize-css/js/chips' {
  declare module.exports: any;
}

declare module 'materialize-css/js/collapsible' {
  declare module.exports: any;
}

declare module 'materialize-css/js/date_picker/picker.date' {
  declare module.exports: any;
}

declare module 'materialize-css/js/date_picker/picker' {
  declare module.exports: any;
}

declare module 'materialize-css/js/dropdown' {
  declare module.exports: any;
}

declare module 'materialize-css/js/forms' {
  declare module.exports: any;
}

declare module 'materialize-css/js/global' {
  declare module.exports: any;
}

declare module 'materialize-css/js/hammer.min' {
  declare module.exports: any;
}

declare module 'materialize-css/js/init' {
  declare module.exports: any;
}

declare module 'materialize-css/js/initial' {
  declare module.exports: any;
}

declare module 'materialize-css/js/jquery.easing.1.3' {
  declare module.exports: any;
}

declare module 'materialize-css/js/jquery.hammer' {
  declare module.exports: any;
}

declare module 'materialize-css/js/jquery.timeago.min' {
  declare module.exports: any;
}

declare module 'materialize-css/js/materialbox' {
  declare module.exports: any;
}

declare module 'materialize-css/js/materialize' {
  declare module.exports: any;
}

declare module 'materialize-css/js/modal' {
  declare module.exports: any;
}

declare module 'materialize-css/js/parallax' {
  declare module.exports: any;
}

declare module 'materialize-css/js/prism' {
  declare module.exports: any;
}

declare module 'materialize-css/js/pushpin' {
  declare module.exports: any;
}

declare module 'materialize-css/js/scrollFire' {
  declare module.exports: any;
}

declare module 'materialize-css/js/scrollspy' {
  declare module.exports: any;
}

declare module 'materialize-css/js/sideNav' {
  declare module.exports: any;
}

declare module 'materialize-css/js/slider' {
  declare module.exports: any;
}

declare module 'materialize-css/js/tabs' {
  declare module.exports: any;
}

declare module 'materialize-css/js/tapTarget' {
  declare module.exports: any;
}

declare module 'materialize-css/js/toasts' {
  declare module.exports: any;
}

declare module 'materialize-css/js/tooltip' {
  declare module.exports: any;
}

declare module 'materialize-css/js/transitions' {
  declare module.exports: any;
}

declare module 'materialize-css/js/velocity.min' {
  declare module.exports: any;
}

declare module 'materialize-css/js/waves' {
  declare module.exports: any;
}

declare module 'materialize-css/package' {
  declare module.exports: any;
}

declare module 'materialize-css/templates/masonry-template/js/init' {
  declare module.exports: any;
}

declare module 'materialize-css/templates/masonry-template/js/masonry.pkgd.min' {
  declare module.exports: any;
}

declare module 'materialize-css/templates/parallax-template/js/init' {
  declare module.exports: any;
}

declare module 'materialize-css/templates/starter-template/js/init' {
  declare module.exports: any;
}

declare module 'materialize-css/tests/spec/autocomplete/autocompleteSpec' {
  declare module.exports: any;
}

declare module 'materialize-css/tests/spec/cards/cardsSpec' {
  declare module.exports: any;
}

declare module 'materialize-css/tests/spec/chips/chipsSpec' {
  declare module.exports: any;
}

declare module 'materialize-css/tests/spec/collapsible/collapsibleSpec' {
  declare module.exports: any;
}

declare module 'materialize-css/tests/spec/dropdown/dropdownSpec' {
  declare module.exports: any;
}

declare module 'materialize-css/tests/spec/helper' {
  declare module.exports: any;
}

declare module 'materialize-css/tests/spec/materialbox/materialboxSpec' {
  declare module.exports: any;
}

declare module 'materialize-css/tests/spec/scrollFire/scrollFireSpec' {
  declare module.exports: any;
}

declare module 'materialize-css/tests/spec/select/selectSpec' {
  declare module.exports: any;
}

declare module 'materialize-css/tests/spec/sideNav/sideNavSpec' {
  declare module.exports: any;
}

declare module 'materialize-css/tests/spec/tabs/tabsSpec' {
  declare module.exports: any;
}

declare module 'materialize-css/tests/spec/toast/toastSpec' {
  declare module.exports: any;
}

declare module 'materialize-css/tests/spec/tooltip/tooltipSpec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'materialize-css/bin/materialize.js' {
  declare module.exports: $Exports<'materialize-css/bin/materialize'>;
}
declare module 'materialize-css/dist/js/materialize.js' {
  declare module.exports: $Exports<'materialize-css/dist/js/materialize'>;
}
declare module 'materialize-css/dist/js/materialize.min.js' {
  declare module.exports: $Exports<'materialize-css/dist/js/materialize.min'>;
}
declare module 'materialize-css/extras/noUiSlider/nouislider.js' {
  declare module.exports: $Exports<'materialize-css/extras/noUiSlider/nouislider'>;
}
declare module 'materialize-css/extras/noUiSlider/nouislider.min.js' {
  declare module.exports: $Exports<'materialize-css/extras/noUiSlider/nouislider.min'>;
}
declare module 'materialize-css/Gruntfile.js' {
  declare module.exports: $Exports<'materialize-css/Gruntfile'>;
}
declare module 'materialize-css/jade/lunr.min.js' {
  declare module.exports: $Exports<'materialize-css/jade/lunr.min'>;
}
declare module 'materialize-css/jade/search.js' {
  declare module.exports: $Exports<'materialize-css/jade/search'>;
}
declare module 'materialize-css/js/animation.js' {
  declare module.exports: $Exports<'materialize-css/js/animation'>;
}
declare module 'materialize-css/js/buttons.js' {
  declare module.exports: $Exports<'materialize-css/js/buttons'>;
}
declare module 'materialize-css/js/cards.js' {
  declare module.exports: $Exports<'materialize-css/js/cards'>;
}
declare module 'materialize-css/js/carousel.js' {
  declare module.exports: $Exports<'materialize-css/js/carousel'>;
}
declare module 'materialize-css/js/character_counter.js' {
  declare module.exports: $Exports<'materialize-css/js/character_counter'>;
}
declare module 'materialize-css/js/chips.js' {
  declare module.exports: $Exports<'materialize-css/js/chips'>;
}
declare module 'materialize-css/js/collapsible.js' {
  declare module.exports: $Exports<'materialize-css/js/collapsible'>;
}
declare module 'materialize-css/js/date_picker/picker.date.js' {
  declare module.exports: $Exports<'materialize-css/js/date_picker/picker.date'>;
}
declare module 'materialize-css/js/date_picker/picker.js' {
  declare module.exports: $Exports<'materialize-css/js/date_picker/picker'>;
}
declare module 'materialize-css/js/dropdown.js' {
  declare module.exports: $Exports<'materialize-css/js/dropdown'>;
}
declare module 'materialize-css/js/forms.js' {
  declare module.exports: $Exports<'materialize-css/js/forms'>;
}
declare module 'materialize-css/js/global.js' {
  declare module.exports: $Exports<'materialize-css/js/global'>;
}
declare module 'materialize-css/js/hammer.min.js' {
  declare module.exports: $Exports<'materialize-css/js/hammer.min'>;
}
declare module 'materialize-css/js/init.js' {
  declare module.exports: $Exports<'materialize-css/js/init'>;
}
declare module 'materialize-css/js/initial.js' {
  declare module.exports: $Exports<'materialize-css/js/initial'>;
}
declare module 'materialize-css/js/jquery.easing.1.3.js' {
  declare module.exports: $Exports<'materialize-css/js/jquery.easing.1.3'>;
}
declare module 'materialize-css/js/jquery.hammer.js' {
  declare module.exports: $Exports<'materialize-css/js/jquery.hammer'>;
}
declare module 'materialize-css/js/jquery.timeago.min.js' {
  declare module.exports: $Exports<'materialize-css/js/jquery.timeago.min'>;
}
declare module 'materialize-css/js/materialbox.js' {
  declare module.exports: $Exports<'materialize-css/js/materialbox'>;
}
declare module 'materialize-css/js/materialize.js' {
  declare module.exports: $Exports<'materialize-css/js/materialize'>;
}
declare module 'materialize-css/js/modal.js' {
  declare module.exports: $Exports<'materialize-css/js/modal'>;
}
declare module 'materialize-css/js/parallax.js' {
  declare module.exports: $Exports<'materialize-css/js/parallax'>;
}
declare module 'materialize-css/js/prism.js' {
  declare module.exports: $Exports<'materialize-css/js/prism'>;
}
declare module 'materialize-css/js/pushpin.js' {
  declare module.exports: $Exports<'materialize-css/js/pushpin'>;
}
declare module 'materialize-css/js/scrollFire.js' {
  declare module.exports: $Exports<'materialize-css/js/scrollFire'>;
}
declare module 'materialize-css/js/scrollspy.js' {
  declare module.exports: $Exports<'materialize-css/js/scrollspy'>;
}
declare module 'materialize-css/js/sideNav.js' {
  declare module.exports: $Exports<'materialize-css/js/sideNav'>;
}
declare module 'materialize-css/js/slider.js' {
  declare module.exports: $Exports<'materialize-css/js/slider'>;
}
declare module 'materialize-css/js/tabs.js' {
  declare module.exports: $Exports<'materialize-css/js/tabs'>;
}
declare module 'materialize-css/js/tapTarget.js' {
  declare module.exports: $Exports<'materialize-css/js/tapTarget'>;
}
declare module 'materialize-css/js/toasts.js' {
  declare module.exports: $Exports<'materialize-css/js/toasts'>;
}
declare module 'materialize-css/js/tooltip.js' {
  declare module.exports: $Exports<'materialize-css/js/tooltip'>;
}
declare module 'materialize-css/js/transitions.js' {
  declare module.exports: $Exports<'materialize-css/js/transitions'>;
}
declare module 'materialize-css/js/velocity.min.js' {
  declare module.exports: $Exports<'materialize-css/js/velocity.min'>;
}
declare module 'materialize-css/js/waves.js' {
  declare module.exports: $Exports<'materialize-css/js/waves'>;
}
declare module 'materialize-css/package.js' {
  declare module.exports: $Exports<'materialize-css/package'>;
}
declare module 'materialize-css/templates/masonry-template/js/init.js' {
  declare module.exports: $Exports<'materialize-css/templates/masonry-template/js/init'>;
}
declare module 'materialize-css/templates/masonry-template/js/masonry.pkgd.min.js' {
  declare module.exports: $Exports<'materialize-css/templates/masonry-template/js/masonry.pkgd.min'>;
}
declare module 'materialize-css/templates/parallax-template/js/init.js' {
  declare module.exports: $Exports<'materialize-css/templates/parallax-template/js/init'>;
}
declare module 'materialize-css/templates/starter-template/js/init.js' {
  declare module.exports: $Exports<'materialize-css/templates/starter-template/js/init'>;
}
declare module 'materialize-css/tests/spec/autocomplete/autocompleteSpec.js' {
  declare module.exports: $Exports<'materialize-css/tests/spec/autocomplete/autocompleteSpec'>;
}
declare module 'materialize-css/tests/spec/cards/cardsSpec.js' {
  declare module.exports: $Exports<'materialize-css/tests/spec/cards/cardsSpec'>;
}
declare module 'materialize-css/tests/spec/chips/chipsSpec.js' {
  declare module.exports: $Exports<'materialize-css/tests/spec/chips/chipsSpec'>;
}
declare module 'materialize-css/tests/spec/collapsible/collapsibleSpec.js' {
  declare module.exports: $Exports<'materialize-css/tests/spec/collapsible/collapsibleSpec'>;
}
declare module 'materialize-css/tests/spec/dropdown/dropdownSpec.js' {
  declare module.exports: $Exports<'materialize-css/tests/spec/dropdown/dropdownSpec'>;
}
declare module 'materialize-css/tests/spec/helper.js' {
  declare module.exports: $Exports<'materialize-css/tests/spec/helper'>;
}
declare module 'materialize-css/tests/spec/materialbox/materialboxSpec.js' {
  declare module.exports: $Exports<'materialize-css/tests/spec/materialbox/materialboxSpec'>;
}
declare module 'materialize-css/tests/spec/scrollFire/scrollFireSpec.js' {
  declare module.exports: $Exports<'materialize-css/tests/spec/scrollFire/scrollFireSpec'>;
}
declare module 'materialize-css/tests/spec/select/selectSpec.js' {
  declare module.exports: $Exports<'materialize-css/tests/spec/select/selectSpec'>;
}
declare module 'materialize-css/tests/spec/sideNav/sideNavSpec.js' {
  declare module.exports: $Exports<'materialize-css/tests/spec/sideNav/sideNavSpec'>;
}
declare module 'materialize-css/tests/spec/tabs/tabsSpec.js' {
  declare module.exports: $Exports<'materialize-css/tests/spec/tabs/tabsSpec'>;
}
declare module 'materialize-css/tests/spec/toast/toastSpec.js' {
  declare module.exports: $Exports<'materialize-css/tests/spec/toast/toastSpec'>;
}
declare module 'materialize-css/tests/spec/tooltip/tooltipSpec.js' {
  declare module.exports: $Exports<'materialize-css/tests/spec/tooltip/tooltipSpec'>;
}
