// flow-typed signature: 417d0c012076ffaee552279f5ef018b7
// flow-typed version: <<STUB>>/youtube-api-search_v0.0.5/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'youtube-api-search'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'youtube-api-search' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'youtube-api-search/index' {
  declare module.exports: $Exports<'youtube-api-search'>;
}
declare module 'youtube-api-search/index.js' {
  declare module.exports: $Exports<'youtube-api-search'>;
}
